### PR TITLE
Pass options to retry package

### PR DESCRIPTION
**Pull request by floatdrop**
To be able set `retries` and stuff.

### CODE REVIEW

**Comment by floatdrop** [comment]
Seems like tests should be rewritten to handle 10 retries.

**Comment by vdemedes** [comment]
10 retries is way too much and long. It needs to see if there is a `retries` key in `options` and set default retry options if it's missing.

**Comment by vdemedes** [comment]
Merging it and going to apply a fix. Thank you!

**Comment by floatdrop** [comment]
:star2:

**Pull request merged**
