### PR TITLE
Update got and retry

### PR DESCRIPTION
**Pull request by zkochan**
I'd love to use this package in [pnpm](https://github.com/rstacruz/pnpm/issues/317) but the dependencies are out of date.

Could you please update got and retry and publish a new version of got-retry?

### CODE REVIEW

**Comment by vdemedes** [comment]
This package got merged into `got` itself, so you can just use `got` directly ;)

**Comment by zkochan** [comment]
You mean this https://github.com/sindresorhus/got/issues/98? Seems like not all of the retry options were ported... pnpm needs the same options that retry has in order to use the npm configs. Anyway, I'll search for a different solution. Maybe a custom retry function

**Comment by vdemedes** [comment]
Oh I see, `got` has only `retries` option. I recommend using `retry` + `got` directly, without in-between dependencies. That way you will be able to customize the behavior exactly the way you need. Wrap `got` in a `retry` operation and that's it ;)

I would reopen this pull request, but this package is no longer maintained, so I would be making you a disservice.

**Comment by zkochan** [comment]
no problem, thanks for the advises!

**Pull request closed without merging**
